language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS="--prefer-stable"

php:
    - 7.2
    - 7.3

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.2.*"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.3.*"
    - php: 7.3
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.2.*"
    - php: 7.3
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.3.*"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
