services:
    # old service names, deprecated
    features.factory: '@Yannickl88\FeaturesBundle\Feature\FeatureFactory'
    features.container:
        alias: Yannickl88\FeaturesBundle\Feature\FeatureContainer
        public: true
    features.tag: '@Yannickl88\FeaturesBundle\Feature\DeprecatedFeature'
    features.twig_extension: '@Yannickl88\FeaturesBundle\Twig\FeaturesExtension'

    Yannickl88\FeaturesBundle\Feature\FeatureFactory:
        - '@Yannickl88\FeaturesBundle\Feature\FeatureContainer'

    Yannickl88\FeaturesBundle\Feature\FeatureContainer:
        public: true
        arguments:
            - "@service_container"
            - [] # replaced by extension
            - [] # replaced by extension

    # alias to allow autowiring the deprecated feature by default
    Yannickl88\FeaturesBundle\Feature\Feature: '@Yannickl88\FeaturesBundle\Feature\DeprecatedFeature'
    Yannickl88\FeaturesBundle\Feature\DeprecatedFeature: ~

    Yannickl88\FeaturesBundle\Twig\FeaturesExtension:
        public: false
        arguments:
            - '@Yannickl88\FeaturesBundle\Feature\FeatureContainer'
        tags:
            - twig.extension
