services:
    Yannickl88\FeaturesBundle\Feature\FeatureFactory:
        - '@Yannickl88\FeaturesBundle\Feature\FeatureContainer'

    Yannickl88\FeaturesBundle\Feature\FeatureContainerInterface: '@Yannickl88\FeaturesBundle\Feature\FeatureContainer'
    Yannickl88\FeaturesBundle\Feature\FeatureContainer:
        public: true
        arguments:
            - '@service_container'
            - [] # Replaced by extension.
            - [] # Replaced by extension.

    # Alias to allow autowiring the deprecated feature by default.
    Yannickl88\FeaturesBundle\Feature\Feature: '@Yannickl88\FeaturesBundle\Feature\DeprecatedFeature'
    Yannickl88\FeaturesBundle\Feature\DeprecatedFeature: ~

    Yannickl88\FeaturesBundle\Twig\FeaturesExtension:
        public: false
        arguments:
            - '@Yannickl88\FeaturesBundle\Feature\FeatureContainer'
        tags:
            - twig.extension
